import { Component, OnInit } from '@angular/core';
import { PdfMakerService } from 'src/app/services/pdf-maker.service';

@Component({
  selector: 'app-punto-once-lista',
  templateUrl: './punto-once-lista.page.html',
  styleUrls: ['./punto-once-lista.page.scss'],
})
export class PuntoOnceListaPage implements OnInit {

  datos: any = {
    check1: false,
    check2: false,
    check3: false,
    check4: false,
    check5: false,
    check6: false,
    check7: false,
    check8: false,
    check9: false,
    check10: false,
    check11: false,
    check12: false,
    check13: false,
    check14: false,
    check15: false,
    check16: false,
    check17: false,
    check18: false,
    check19: false,
    check20: false,
    check21: false,
    check22: false,
    check23: false,
    check24: false,
    check25: false,
    check26: false,
    check27: false,
    check28: false,
    check29: false,
    num1: '',
    num2: '',
    num3: '',
    num4: '',
    num5: '',
    num6: '',
    num7: '',
    num8: '',
    num9: '',
    num10: '',
    num11: '',
    num12: '',
    num13: '',
    num14: '',
    num15: '',
    num16: '',
    num17: '',
    num18: '',
};

  constructor( private pdfMaker: PdfMakerService ) { }

  ngOnInit() {
  }

  enviarForm(formulario) {
    console.log(this.datos);
  }

  pdf() {
    const dd = {
      header: function() {
        return {
          table: {
            widths: [740], heights: [50, 15, 15],
            body: [
              [{text: ''}],
              [{text: 'XI. INTEGRIDAD MECÁNICA', alignment: 'center', bold: true}],
              [{text: 'INFORMACIÓN DE LOS EQUIPOS', alignment: 'center', bold: true, fillColor: '#ddd'}],
            ]
          },
          margin: [22, 15]
        };
      },
      footer: function() {
        return {
          table: {
            headerRows: 1,
            widths: [750],
            body : [
              [''],
              [''],
              ['']
            ]
          },
          layout : 'headerLineOnly',
          margin: [30, 85]
        };
      },
      content: [
        {
            table: {
                widths: [250, 20, 200, 200],
                body: [
                    [
                        {text: 'PRODUCTO MANEJADO', fillColor: '#ddd', bold: true, colSpan: 2},
                        {},
                        {text: 'NO. DE TANQUES', fillColor: '#ddd', bold: true},
                        {text: 'NO. DE DISPENSARIOS POR TANQUE', fillColor: '#ddd', bold: true},
                    ],
                    [
                        {text: 'MAGNA'},
                        {text: `${this.datos.CH1}`, alignment: 'center'},
                        {text: '', alignment: 'center'},
                        {text: '', alignment: 'center'},
                    ],
                    [
                        {text: 'PREMIUM'},
                        {text: '', alignment: 'center'},
                        {text: '', alignment: 'center'},
                        {text: '', alignment: 'center'},
                    ],
                    [
                        {text: 'DIESEL'},
                        {text: '', alignment: 'center'},
                        {text: '', alignment: 'center'},
                        {text: '', alignment: 'center'},
                    ],
                ]
            },
        },
        {text: '\n'},
        {
          table: {
              widths: [30, 150, 60, 310, 45, 45, 45],
              body: [
                [
                    {text: 'NO.', bold: true, fillColor: '#ddd', alignment: 'center'},
                    {text: 'TIPO DE EQUIPO', bold: true, fillColor: '#ddd'},
                    {text: 'CANTIDAD', bold: true, fillColor: '#ddd'},
                    {text: 'DESCRIPCIÓN', bold: true, fillColor: '#ddd'},
                    {text: 'PRODUCTO', bold: true, fillColor: '#ddd', colSpan: 3},
                    {},
                    {}
                ],
                [
                    {text: '1', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '2', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '3', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '4', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '5', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '6', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '7', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '8', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '9', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '10', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '11', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '12', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '13', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '14', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '15', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '16', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '17', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '18', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '19', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '20', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '21', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '22', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '23', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '24', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '25', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '26', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '27', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '28', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '29', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '30', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
              ]
          }
        },
      ],
      pageOrientation: 'landscape',
      pageSize: 'LETTER',
      pageMargins: [22, 120]
    };
    this.pdfMaker.generate(dd, 'Equipos');
  }
}
