import { Component, OnInit } from '@angular/core';
import { PdfMakerService } from 'src/app/services/pdf-maker.service';

@Component({
  selector: 'app-punto-once',
  templateUrl: './punto-once.page.html',
  styleUrls: ['./punto-once.page.scss'],
})
export class PuntoOncePage implements OnInit {


  constructor( private pdfMaker: PdfMakerService) { }

  ngOnInit() {
  }

  enviarForm(formulario) {
    console.log();
  }

  pdf() {
    const dd = {
      header: function() {
        return {
          table: {
            widths: [740], heights: [50, 15, 15],
            body: [
              [{text: ''}],
              [{text: 'XI. INTEGRIDAD MECÁNICA', alignment: 'center', bold: true}],
              [{text: 'INFORMACIÓN DE LOS EQUIPOS', alignment: 'center', bold: true, fillColor: '#ddd'}],
            ]
          },
          margin: [22, 15]
        };
      },
      footer: function() {
        return {
          table: {
            headerRows: 1,
            widths: [750],
            body : [
              [''],
              [''],
              ['']
            ]
          },
          layout : 'headerLineOnly',
          margin: [30, 85]
        };
      },
      content: [
        {
          table: {
              widths: [30, 150, 60, 310, 45, 45, 45],
              body: [
                [
                    {text: 'NO.', bold: true, fillColor: '#ddd', alignment: 'center'},
                    {text: 'TIPO DE EQUIPO', bold: true, fillColor: '#ddd'},
                    {text: 'CANTIDAD', bold: true, fillColor: '#ddd'},
                    {text: 'DESCRIPCIÓN', bold: true, fillColor: '#ddd'},
                    {text: 'PRODUCTO', bold: true, fillColor: '#ddd', colSpan: 3},
                    {},
                    {}
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
                [
                    {text: '', alignment: 'center'},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                    {text: ''},
                ],
              ]
          }
        },
      ],
      pageOrientation: 'landscape',
      pageSize: 'LETTER',
      pageMargins: [22, 120]
    };
    this.pdfMaker.generate(dd, 'Equipos');
  }
}
