import { Component, OnInit } from "@angular/core";
import { NavController } from "@ionic/angular";
import { PdfMakerService } from "src/app/services/pdf-maker.service";

@Component({
  selector: "app-fo08",
  templateUrl: "./fo08.page.html",
  styleUrls: ["./fo08.page.scss"]
})
export class Fo08Page implements OnInit {

  datos:any = {
    check1:'',
    check2:'',
    check3:'',
    check4:'',
    check5:'',
    check6:'',
    check7:'',
    check8:'',
    check9:'',
    check10:'',
    check11:'',
    check12:'',
    check13:'',
    check14:'',
    check15:'',
    check16:'',
    check17:'',
    check18:'',
    check19:'',
    check20:'',
    check21:'',
    check22:'',
    check23:'',
    check24:'',
    check25:'',
    check26:'',
    check27:'',
    check28:'',
    check29:'',
    check30:'',
    check31:'',
    check32:'',
    check33:'',
    check34:'',
    check35:'',
    check36:'',
    check37:'',
    check38:'',
    check39:'',
    check40:'',
    check41:'',
    check42:'',
    check43:'',
    check44:'',
    check45:'',
    check46:'',
    check47:'',
    check48:'',
    check49:'',
    check50:'',
    check51:'',
    check52:'',
    check53:'',
    check54:'',
    check55:'',
    check56:'',
    check57:'',
    check58:'',
    check59:'',
    check60:'',
    check61:'',
    check62:'',
    check63:'',
    check64:'',
    check65:'',
    check66:'',
    check67:'',
    check68:'',
    check69:'',
    check70:'',
    check71:'',
    check72:'',
    check73:'',
    check74:'',
    check75:'',
    check76:'',
    check77:'',
    check78:'',
    check79:'',
    check80:'',
    check81:'',
    check82:'',
    check83:'',
    check84:'',
    check85:'',
    check86:'',
    check87:'',
    check88:'',
    check89:'',
    check90:'',
    check91:'',
    check92:'',
    check93:'',
    check94:'',
    check95:'',
    check96:'',
    check97:'',
    check98:'',
    check99:'',
    check100:'',
    check101:'',
    check102:'',
    check103:'',
    check104:'',
    check105:'',
    check106:'',
    check107:'',
    check108:'',
    check109:'',
    check110:'',
    check111:'',
    check112:'',
    check113:'',
    check114:'',
    check115:'',
    check116:'',
    check117:'',
    check118:'',
    check119:'',
    check120:'',
    check121:'',
    check122:'',
    check123:'',
    check124:'',
    check125:'',
    check126:'',
    check127:'',
    check128:'',
    check129:'',
    check130:'',
    check131:'',
    check132:'',
    check133:'',
    check134:'',
    check135:'',
    check136:'',
    check137:'',
    check138:'',
    check139:'',
    check140:'',
    check141:'',
    check142:'',
    check143:'',
    check144:'',
    check145:'',
    check146:'',
    check147:'',
    check148:'',
    check149:'',
    check150:'',
    check151:'',
    check152:'',
    check153:'',
    check154:'',
    check155:'',
    check156:'',
    check157:'',
    check158:'',
    check159:'',
    check160:'',
    check161:'',
    check162:'',
    check163:'',
    check164:'',
    check165:'',
    check166:'',
    check167:'',
    check168:'',
    check169:'',
    check170:'',
    check171:'',
    check172:'',
    check173:'',
    check174:'',
    check175:'',
    check176:'',
    check177:'',
    check178:'',
    check179:'',
    check180:'',
    check181:'',
    check182:'',
    check183:'',
    check184:'',
    check185:'',
    check186:'',
    check187:'',
    check188:'',
    check189:'',
    check190:'',
    check191:'',
    check192:'',
    check193:'',
    check194:'',
    check195:'',
    check196:'',
    check197:'',
    check198:'',
    check199:'',
    check200:'',
    check201:'',
    check202:'',
    check203:'',
    check204:'',
    check205:'',
    check206:'',
    check207:'',
    check208:'',
    check209:'',
    check210:'',
    check211:'',
    check212:'',
    check213:'',
    check214:'',
    check215:'',
    check216:'',
    check217:'',
    check218:'',
    check219:'',
    check220:'',
    check221:'',
    check222:'',
    check223:'',
    check224:'',
    check225:'',
    check226:'',
    check227:'',
    check228:'',
    check229:'',
    check230:'',
    check231:'',
    check232:'',
    check233:'',
    check234:'',
    check235:'',
    check236:'',
    check237:'',
    check238:'',
    check239:'',
    check240:'',
    check241:'',
    check242:'',
    check243:'',
    check244:'',
    check245:'',
    check246:'',
    check247:'',
    check248:'',
    check249:'',
    check250:'',
    check251:'',
    check252:'',
    check253:'',
    check254:'',
    check255:'',
    check256:'',
    check257:'',
    check258:'',
    check259:'',
    check260:'',
    check261:'',
    check262:'',
    check263:'',
    check264:'',
    check265:'',
    check266:'',
    check267:'',
    check268:'',
    check269:'',
    check270:'',
    check271:'',
    check272:'',
    check273:'',
    check274:'',
    check275:'',
    check276:'',
    check277:'',
    check278:'',
    check279:'',
    check280:'',
    check281:'',
    check282:'',
    check283:'',
    check284:'',
    check285:'',
    check286:'',
    check287:'',
    check288:'',
    check289:'',
    check290:'',
    check291:'',
    check292:'',
    check293:'',
    check294:'',
    check295:'',
    check296:'',
    check297:'',
    check298:'',
    check299:'',
    check300:'',
    check301:'',
    check302:'',
    check303:'',
    check304:'',
    check305:'',
    check306:'',
    check307:'',
    check308:'',
    check309:'',
    check310:'',
    check311:'',
    check312:'',
    check313:'',
    check314:'',
    check315:'',
    check316:'',
    check317:'',
    check318:'',
    check319:'',
    check320:'',
    check321:'',
    check322:'',
    check323:'',
    check324:'',
    check325:'',
    check326:'',
    check327:'',
    check328:'',
    check329:'',
    check330:'',
    check331:'',
    check332:'',
    check333:'',
    check334:'',
    check335:'',
    check336:'',
    check337:'',
    check338:'',
    check339:'',
    check340:'',
    check341:'',
    check342:'',
    check343:'',
    check344:'',
    check345:'',
    check346:'',
    check347:'',
    check348:'',
    check349:'',
    check350:'',
    check351:'',
    check352:'',
    check353:'',
    check354:'',
    check355:'',
    check356:'',
    check357:'',
    check358:'',
    check359:'',
    check360:'',
    check361:'',
    check362:'',
    check363:'',
    check364:'',
    check365:'',
    check366:'',
    check367:'',
    check368:'',
    check369:'',
    check370:'',
    check371:'',
    check372:'',
    check373:'',
    check374:'',
    check375:'',
    check376:'',
    check377:'',
    check378:'',
    check379:'',
    check380:'',
    check381:'',
    check382:'',
    check383:'',
    check384:'',
    check385:'',
    check386:'',
    check387:'',
    check388:'',
    check389:'',
    check390:'',
    check391:'',
    check392:'',
    check393:'',
    check394:'',
    check395:'',
    check396:'',
    check397:'',
    check398:'',
    check399:'',
    check400:'',
    check401:'',
    check402:'',
    check403:'',
    check404:'',
    check405:'',
    check406:'',
    check407:'',
    check408:'',
    check409:'',
    check410:'',
    check411:'',
    check412:'',
    check413:'',
    check414:'',
    check415:'',
    check416:'',
    check417:'',
    check418:'',
    check419:'',
    check420:'',
    check421:'',
    check422:'',
    check423:'',
    check424:'',
    check425:'',
    check426:'',
    check427:'',
    check428:'',
  }

  constructor(
    private navCtrl: NavController,
    private pdfMaker: PdfMakerService
  ) {}

  ngOnInit() {}

  pdf() {
    console.log("hola mundo");
    var dd = {
      background: function(currentPage, pageSize) {
        return {
        //   image: "sampleImage.jpg",
        //   width: 750,
        //   absolutePosition: { x: 10, y: 80 },
        //   opacity: 0.3
         };
      },
      header: function() {
        return {
          table: {
            widths: [560],
            heights: [50, 15, 15],

            body: [
              [{}],
              [
                {
                  text: "XI. INTEGRIDAD MECÁNICA Y ASEGURAMIENTO DE LA CALIDAD",
                  alignment: "center",
                  bold: true
                }
              ],
              [
                {
                  text: "INSPECCIÓN MENSUAL DE EXTINTORES",
                  alignment: "center",
                  bold: true,
                  fillColor: "#ddd"
                }
              ]
            ]
          },
          margin: [22, 15]
        };
      },
      footer: function() {
        return {
          table: {
            headerRows: 1,
            widths: [560],
            body: [[""], [""], [""]]
          },
          layout: "headerLineOnly",
          margin: [30, 85]
        };
      },

      content: [
        {
          table: {
            widths: [
              150,
              150,
              10,
              10,
              10,
              10,
              10,
              10,
              10,
              10,
              10,
              10,
              10,
              9,
              10
            ],
            body: [
              [
                { text: "DESCRIPCIÓN", bold: true },
                { text: "AREA/IMAGEN", bold: true },
                { text: "ALMACENAMIENTO", bold: true },
                { text: "DISPENSARIOS", bold: true },
                { text: "OFICINAS", bold: true },
                { text: "CUARTO \nDE \n CONTROL", bold: true },
                { text: "CUARTO\n DE\n MÁQUINAS", bold: true },
                { text: "ALMACEN\n DE\n RESIDUOS\n PEL.", bold: true },
                { text: "FACTURACIÓN", bold: true },
                { text: "ACCESOS\n Y\n VIALIDADES", bold: true },
                { text: "ESTACIONAMIENTO", bold: true },
                { text: "SANITARIOS", bold: true },
                { text: "BODEGAS\n DE\n ACEITES", bold: true },
                { text: "CAMBIO\n DE\n ACEITE", bold: true },
                { text: "PUNTO\n DE\n REUNION", bold: true }
              ],
              [
                { text: "PROHIBIDO FUMAR" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "VERIFIQUE MARQUE CEROS" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "APAGUE EL MOTOR" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "PROHIBIDO USO DE CELULAR" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "EXTINTOR" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "PARO DE EMERENCIA" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "AGUA   AIRE" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "CIRCULACIÓN" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "BASURA" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "VELOCIDAD MÁXIMA 10 KM/HR", pageBreak: "before" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "NO ESTACIONARSE" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "PELIGRO DESCARGANDO COMBUSTIBLE" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "REGISTRO DE PREMIUM EN TANQUE" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "REGISTRO DE MAGNA EN TANQUE" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "REGISTRO DE DIÉSEL EN TANQUE" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "TUBERIA DE MAGNA EN VENTEO Y DISPENSARIO" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "TUBERIA DE PREMIUM EN VENTEO Y DISPENSARIO" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "TUBERIA DE DIÉSEL EN VENTEO Y DISPENSARIO(NEGRO)" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "PUESTA A TIERRA" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "POZO DE OBSERVACIÓN" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "POZO DE MONITOREO(AMARILLO)" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "ALTO VOLTAJE" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "PROHIBIDO EL PASO A PERSONAL AJENO" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "DRENAJE PLUVIAL(AZUL)" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "DRENAJE ACEITOSO" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "AMACÉN DE RESIDUOS PELIGROSOS" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "CIRCULACIÓN EN PISOS" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "RECTANGULO EN ÁREA DE DESPACHO", pageBreak: "before" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "GUARNICIÓN Y DELIMITACIÓN" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "ESTACIONAMIENTO RAMPA PARA DISCAPACITADOS" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "ESTACIONAMIENTO" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "SANITARIOS" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "RUTA DE EVACUACIÓN" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ],
              [
                { text: "PUNTO DE REUNIÓN" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" },
                { text: "" }
              ]
            ]
          }
        },
        {
          text: "\n"
        },
        {
          table: {
            widths: [400, 150],
            heights: [40],
            body: [
              [
                {
                  text:
                    "\n\n\n\nCinthya Karime Bedoy DÍaz \nENCARGADO DE LA ESTACIÓN DE SERVICIO"
                },
                { text: "\n FECHA 00/00/0000" }
              ]
            ]
          }
        }
      ],
      pageSize: "LETTER",
      pageMargins: [22, 120]
    };
    this.pdfMaker.generate(dd, "XI.FO-07 INSPECCIÓN MENSUAL DE EXTINTORES.pdf");
  }
}
