import { Component, OnInit, ViewChild } from '@angular/core';
import { IonSlides, IonInfiniteScroll } from '@ionic/angular';
import { PdfMakerService } from 'src/app/services/pdf-maker.service';

@Component({
  selector: 'app-punto-ocho',
  templateUrl: './punto-ocho.page.html',
  styleUrls: ['./punto-ocho.page.scss'],
})
export class PuntoOchoPage implements OnInit {
  datos:any={
c1p1:'',  
c1p2:'',
c1p3:'',
c1p4:'',
c1p5:'',
c1p6:'',
c1p7:'',
c1p8:'',
c1p9:'',
c2p1:'',  
c2p2:'',
c2p3:'',
c2p4:'',
c2p5:'',
c2p6:'',
c2p7:'',
c2p8:'',
c2p9:'',
c3p1:'',  
c3p2:'',
c3p3:'',
c3p4:'',
c3p5:'',
c3p6:'',
c3p7:'',
c3p8:'',
c3p9:'',
c4p1:'',  
c4p2:'',
c4p3:'',
c4p4:'',
c4p5:'',
c4p6:'',
c4p7:'',
c4p8:'',
c4p9:'',
c5p1:'',  
c5p2:'',
c5p3:'',
c5p4:'',
c5p5:'',
c5p6:'',
c5p7:'',
c5p8:'',
c5p9:'',
c6p1:'',  
c6p2:'',
c6p3:'',
c6p4:'',
c6p5:'',
c6p6:'',
c6p7:'',
c6p8:'',
c6p9:'',
c7p1:'',  
c7p2:'',
c7p3:'',
c7p4:'',
c7p5:'',
c7p6:'',
c7p7:'',
c7p8:'',
c7p9:'',
c8p1:'',  
c8p2:'',
c8p3:'',
c8p4:'',
c8p5:'',
c8p6:'',
c8p7:'',
c8p8:'',
c8p9:'',
c9p1:'',  
c9p2:'',
c9p3:'',
c9p4:'',
c9p5:'',
c9p6:'',
c9p7:'',
c9p8:'',
c9p9:'',
c10p1:'',  
c10p2:'',
c10p3:'',
c10p4:'',
c10p5:'',
c10p6:'',
c10p7:'',
c10p8:'',
c10p9:'',
c11p1:'',  
c11p2:'',
c11p3:'',
c11p4:'',
c11p5:'',
c11p6:'',
c11p7:'',
c11p8:'',
c11p9:'',
c12p1:'',  
c12p2:'',
c12p3:'',
c12p4:'',
c12p5:'',
c12p6:'',
c12p7:'',
c12p8:'',
c12p9:'',
c13p1:'',  
c13p2:'',
c13p3:'',
c13p4:'',
c13p5:'',
c13p6:'',
c13p7:'',
c13p8:'',
c13p9:'',
c13p10:'',  
c13p11:'',
c13p12:'',
c13p13:'',
c13p14:'',
c13p15:'',
c14p1:'',  
c14p2:'',
c14p3:'',
c14p4:'',
c14p5:'',
c14p6:'',
c14p7:'',
c14p8:'',
c14p9:'',
c14p10:'',  
c14p11:'',
c14p12:'',
c14p13:'',
c14p14:'',
c14p15:'',
c15p1:'',  
c15p2:'',
c15p3:'',
c15p4:'',
c15p5:'',
c15p6:'',
c15p7:'',
c15p8:'',
c15p9:'',
c15p10:'',  
c15p11:'',
c15p12:'',
c15p13:'',
c15p14:'',
c15p15:'',
c16p1:'',  
c16p2:'',
c16p3:'',
c16p4:'',
c16p5:'',
c16p6:'',
c16p7:'',
c16p8:'',
c16p9:'',
c16p10:'',  
c16p11:'',
c16p12:'',
c16p13:'',
c16p14:'',
c16p15:'',
c17p1:'',  
c17p2:'',
c17p3:'',
c17p4:'',
c17p5:'',
c17p6:'',
c17p7:'',
c17p8:'',
c17p9:'',
c17p10:'',  
c17p11:'',
c17p12:'',
c17p13:'',
c17p14:'',
c17p15:'',
c18p1:'',  
c18p2:'',
c18p3:'',
c18p4:'',
c18p5:'',
c18p6:'',
c18p7:'',
c18p8:'',
c18p9:'',
c18p10:'',  
c18p11:'',
c18p12:'',
c18p13:'',
c18p14:'',
c18p15:'',
c19p1:'',  
c19p2:'',
c19p3:'',
c19p4:'',
c19p5:'',
c19p6:'',
c19p7:'',
c19p8:'',
c19p9:'',
c19p10:'',  
c19p11:'',
c19p12:'',
c19p13:'',
c19p14:'',
c19p15:'',
c20p1:'',  
c20p2:'',
c20p3:'',
c20p4:'',
c20p5:'',
c20p6:'',
c20p7:'',
c20p8:'',
c20p9:'',
c20p10:'',  
c20p11:'',
c20p12:'',
c20p13:'',
c20p14:'',
c20p15:'',
c21p1:'',  
c21p2:'',
c21p3:'',
c21p4:'',
c21p5:'',
c21p6:'',
c21p7:'',
c21p8:'',
c21p9:'',
c21p10:'',  
c21p11:'',
c21p12:'',
c21p13:'',
c21p14:'',
c21p15:'',
c22p1:'',  
c22p2:'',
c22p3:'',
c22p4:'',
c22p5:'',
c22p6:'',
c22p7:'',
c22p8:'',
c22p9:'',
c22p10:'',  
c22p11:'',
c22p12:'',
c22p13:'',
c22p14:'',
c22p15:'',
c23p1:'',  
c23p2:'',
c23p3:'',
c23p4:'',
c23p5:'',
c23p6:'',
c23p7:'',
c23p8:'',
c23p9:'',
c23p10:'',  
c23p11:'',
c23p12:'',
c23p13:'',
c23p14:'',
c23p15:'',
c24p1:'',  
c24p2:'',
c24p3:'',
c24p4:'',
c24p5:'',
c24p6:'',
c24p7:'',
c24p8:'',
c24p9:'',
c24p10:'',  
c24p11:'',
c24p12:'',
c24p13:'',
c24p14:'',
c24p15:'',
c25p1:'',  
c25p2:'',
c25p3:'',
c25p4:'',
c25p5:'',


  }
  @ViewChild('slider') slider: IonSlides
  @ViewChild(IonInfiniteScroll) InfiniteScroll:IonInfiniteScroll;

  constructor( private pdfMaker: PdfMakerService,) { }

  ngOnInit() {
  }

  enviarForm(formulario){
    console.log(this.datos);
    console.log('hola si funciona el form');
    
    
  }

  pdf(){

    console.log('funciona en pdf');
    
    var dd = {
    //   background: function(currentPage, pageSize) {
    //   return {image: 'sampleImage.jpg', width: 790,height: 775, absolutePosition: {x: 0, y: 0},opacity: 0.5}
    // },
      header: function(){
        return {
            table: { widths: [745],heights:[30,0,0],
  body: [
  
      [{text:''}],
      [{text:'VIII. CONTROL DE DOCUMENTOS Y REGISTROS',alignment:'center',bold:true}],
      [{text:'SOLICITUD DE CAMBIOS',alignment:'center',bold:true,fillColor:'#ddd'}],
  ]
  
  }, margin: [22,15]
        };
      },
      footer: function(){
        return {
            table:{
     headerRows:1, 
     widths: [560],
               body : [
               [''],
               [''],
               ['']
                   ]
          }, layout : 'headerLineOnly',
            margin: [30,100]
        };
      },
      
      content:[
              {
                  table:{
                      widths: [45,450,60,60,60,70],
                      body:[
                          [{text:'PROCEDIMIENTOS DEL SISTEMA',alignment:'center',bold:true,fillColor:'#ddd',colSpan:5},{text:''},{text:''},{text:''},{text:''},],
                          [{text:'CLAVE',bold:true,fillColor:'#ddd'},{text:'DESCRIPCION DEL DOCUMENTO',bold:true,fillColor:'#ddd'},{text:'FECHA DE EMISIÓN',bold:true,fillColor:'#ddd'},{text:'FECHA DE REVISIÓN',bold:true,fillColor:'#ddd'},{text:'NO. DE REVISION',bold:true,fillColor:'#ddd'},],
                          [{text:'P-SA-01',fontSize:10},{text:'POLÍTICA',fontSize:10},{text:`${this.datos.c1p1}`},{text:`${this.datos.c1p2}`},{text:`${this.datos.c1p3}`},],
                          [{text:'P-SA-02',fontSize:10},{text:'IDENTIFICACIÓN DE PELIGROS Y DE ASPECTOS AMBIENTALES PARA LA EVALUACIÓN DE RIESGOS Y DE IMPACTOS AMBIENTALES',fontSize:10},{text:`${this.datos.c1p4}`},{text:`${this.datos.c1p5}`},{text:`${this.datos.c1p6}`},],
                          [{text:'P-SA-03',fontSize:10},{text:'REQUISITOS LEGALES',fontSize:10},{text:`${this.datos.c1p7}`},{text:`${this.datos.c1p8}`},{text:`${this.datos.c1p9}`},],
                          [{text:'P-SA-04',fontSize:10},{text:'OBJETIVOS, METAS E INDICADORES.',fontSize:10},{text:`${this.datos.c2p1}`},{text:`${this.datos.c2p2}`},{text:`${this.datos.c2p3}`},],
                          [{text:'P-SA-05',fontSize:10},{text:'PFUNCIONES, RESPONSABILIDADES Y AUTORIDAD',fontSize:10},{text:`${this.datos.c2p4}`},{text:`${this.datos.c2p5}`},{text:`${this.datos.c2p6}`},],
                          [{text:'P-SA-06',fontSize:10},{text:'COMPETENCIA DEL PERSONAL, CAPACITACIÓN Y ENTRENAMIENTO',fontSize:10},{text:`${this.datos.c3p7}`},{text:`${this.datos.c3p8}`},{text:`${this.datos.c3p9}`},],
                          [{text:'P-SA-07',fontSize:10},{text:'COMUNICACIÓN, PARTICIPACIÓN Y CONSULTA.',fontSize:10},{text:`${this.datos.c4p1}`},{text:`${this.datos.c4p2}`},{text:`${this.datos.c4p3}`},],
                          [{text:'P-SA-08',fontSize:10},{text:'CONTROL DE DOCUMENTOS Y REGISTROS.',fontSize:10},{text:`${this.datos.c4p4}`},{text:`${this.datos.c4p5}`},{text:`${this.datos.c4p6}`},],
                          [{text:'P-SA-09',fontSize:10},{text:'PMEJORES PRÁCTICAS Y ESTÁNDARES.',fontSize:10},{text:`${this.datos.c4p7}`},{text:`${this.datos.c4p8}`},{text:`${this.datos.c4p9}`},],
                          [{text:'P-SA-10',fontSize:10},{text:'CONTROL DE ACTIVIDADES Y PROCESOS.',fontSize:10},{text:`${this.datos.c5p1}`},{text:`${this.datos.c5p2}`},{text:`${this.datos.c5p3}`},],
                          [{text:'P-SA-11',fontSize:10},{text:'INTEGRIDAD MECÁNICA Y ASEGURAMIENTO DE LA CALIDAD.',fontSize:10},{text:`${this.datos.c5p4}`},{text:`${this.datos.c5p5}`},{text:`${this.datos.c5p6}`},],
                          [{text:'P-SA-12',fontSize:10},{text:'SEGURIDAD DE CONTRATISTAS',fontSize:10},{text:`${this.datos.c5p7}`},{text:`${this.datos.c5p8}`},{text:`${this.datos.c5p9}`},],
                          [{text:'P-SA-13',fontSize:10},{text:'PREPARACIÓN Y RESPUESTA A EMERGENCIAS.'},{text:`${this.datos.c6p1}`},{text:`${this.datos.c6p2}`},{text:`${this.datos.c6p3}`},],
                           [{text:'P-SA-14',fontSize:10},{text:'MONITOREO, VERIFICACIÓN Y EVALUACIÓN.'},{text:`${this.datos.c6p4}`},{text:`${this.datos.c6p5}`},{text:`${this.datos.c6p6}`},],
                          [{text:'P-SA-15',fontSize:10},{text:'AUDITORÍAS.'},{text:`${this.datos.c6p7}`},{text:`${this.datos.c6p8}`},{text:`${this.datos.c6p9}`},],
                          [{text:'P-SA-16',fontSize:10},{text:'INVESTIGACIÓN DE INCIDENTES Y ACCIDENTES.',fontSize:10},{text:`${this.datos.c7p1}`},{text:`${this.datos.c7p2}`},{text:`${this.datos.c7p3}`},],
                          [{text:'P-SA-17',fontSize:10},{text:'REVISIÓN DE RESULTADOS',fontSize:10},{text:`${this.datos.c7p4}`},{text:`${this.datos.c7p5}`},{text:`${this.datos.c7p6}`},],
                          [{text:'P-SA-18',fontSize:10},{text:'INFORMES DE DESEMPEÑO.',fontSize:10},{text:`${this.datos.c7p7}`},{text:`${this.datos.c7p8}`},{text:`${this.datos.c7p9}`},]
                         ]
                  }
              },
              {
                text:'\n'  
              },
              {
                  table:{
                      widths: [45,450,60,60,60,70],
                      body:[
                          [{text:'PROCEDIMIENTOS DEL SISTEMA',alignment:'center',bold:true,fillColor:'#ddd',colSpan:5},{text:''},{text:''},{text:''},{text:''},],
                          [{text:'CLAVE',bold:true,fillColor:'#ddd'},{text:'DESCRIPCION DEL DOCUMENTO',bold:true,fillColor:'#ddd'},{text:'FECHA DE EMISIÓN',bold:true,fillColor:'#ddd'},{text:'FECHA DE REVISIÓN',bold:true,fillColor:'#ddd'},{text:'NO. DE REVISION',bold:true,fillColor:'#ddd'},],
                          [{text:'P-OP-01',fontSize:10},{text:'RECEPCION DE AUTOTANQUE Y DESCARGA DE PODUCTOS A TANQUES DE ALMACENAMIENTO',fontSize:10},{text:`${this.datos.c8p1}`},{text:`${this.datos.c8p2}`},{text:`${this.datos.c8p3}`},],
                          [{text:'P-OP-02',fontSize:10},{text:'DESPACHO DE PRODUCTOS INFLAMABLES Y COMBUSTIBLES A VEHÍCULOS',fontSize:10},{text:`${this.datos.c8p4}`},{text:`${this.datos.c8p5}`},{text:`${this.datos.c8p6}`},],
                          [{text:'P-TS-01',fontSize:10},{text:'ETIQUETA, CANDADEO Y BLOQUEO PARA INTERRUPCIÓN DE LÍNEAS ELÉCTRICAS',fontSize:10},{text:`${this.datos.c8p7}`},{text:`${this.datos.c8p8}`},{text:`${this.datos.c8p9}`},],
                          [{text:'P-TS-02',fontSize:10},{text:'ETIQUETA, CANDADEO Y BLOQUEO PARA INTERRPCIÓN DE LÍNEAS CON PRODUCTO',fontSize:10},{text:`${this.datos.c9p1}`},{text:`${this.datos.c9p2}`},{text:`${this.datos.c9p3}`},],
                          [{text:'P-TS-03',fontSize:10},{text:'TRABAJOS CON HERRAMIENTAS QUE GENEREN FUENTES DE IGNICION',fontSize:10},{text:`${this.datos.c9p4}`},{text:`${this.datos.c9p5}`},{text:`${this.datos.c9p6}`},],
                          [{text:'P-TS-04',fontSize:10},{text:'TRABAJOS EN ESCALERAS O PLATAFORMAS EN ALTURAS MAYORES A 1.5 m.',fontSize:10},{text:`${this.datos.c9p7}`},{text:`${this.datos.c9p8}`},{text:`${this.datos.c9p9}`},],
                          [{text:'P-TS-05',fontSize:10},{text:'TRABAJOS EN ÁREAS CONFINADAS',fontSize:10},{text:`${this.datos.c10p1}`},{text:`${this.datos.c10p2}`},{text:`${this.datos.c10p3}`},],
                          [{text:'P-TS-06',fontSize:10},{text:'PERMISO DE TRABAJOS PELIGROSOS',fontSize:10},{text:`${this.datos.c10p4}`},{text:`${this.datos.c10p5}`},{text:`${this.datos.c10p6}`},],
                          [{text:'P-CP-01',fontSize:10},{text:'ADMINISTRACIÓN DE CAMBIOS DE PERSONAL',fontSize:10},{text:`${this.datos.c10p7}`},{text:`${this.datos.c10p8}`},{text:`${this.datos.c10p9}`},],
                          [{text:'P-CT-01',fontSize:10},{text:'ADMINISTRACION DE CAMBIOS DE TECNOLOGÍA',fontSize:10},{text:`${this.datos.c11p1}`},{text:`${this.datos.c11p2}`},{text:`${this.datos.c11p3}`},],
                          [{text:'P-IM-01',fontSize:10},{text:'MANTENIMIENTO A DISPENSARIOS',fontSize:10},{text:`${this.datos.c11p4}`},{text:`${this.datos.c11p5}`},{text:`${this.datos.c11p6}`},],
                          [{text:'P-IM-02',fontSize:10},{text:'MANTENIMIENTO A TANQUES',fontSize:10},{text:`${this.datos.c11p7}`},{text:`${this.datos.c11p8}`},{text:`${this.datos.c11p9}`},],
                          [{text:'P-IM-03',fontSize:10},{text:'MANTENIMIENTO A INSTALACIONES ELÉCTRICAS',fontSize:10},{text:`${this.datos.c12p1}`},{text:`${this.datos.c12p2}`},{text:`${this.datos.c12p3}`},],
                           [{text:'P-IM-04',fontSize:10},{text:'MANTENIMIENTO A EDIFICIOS',fontSize:10},{text:`${this.datos.c12p4}`},{text:`${this.datos.c12p5}`},{text:`${this.datos.c12p6}`},],
                          [{text:'P-IM-05',fontSize:10},{text:'MANTENIMIENTO A DRENAJES.',fontSize:10},{text:`${this.datos.c12p7}`},{text:`${this.datos.c12p8}`},{text:`${this.datos.c12p9}`},],
                          [{text:'P-IM-06',fontSize:10},{text:'MANTENIMIENTO A MAQUINAS',fontSize:10},{text:''},{text:''},{text:''},],
                          [{text:'P-RE-01',fontSize:10},{text:'PLANES DE RESPUESTA A EMERGENCIAS.',fontSize:10},{text:''},{text:''},{text:''},],
                         [{text:'P-CR-01',fontSize:10},{text:'METODOLOGÍA DEL ARBOL DE FALLAS',fontSize:10},{text:''},{text:''},{text:''},],
                         [{},{},{},{},{text:'',pageBreak:'before'}]
                         ]
                  }
              },{
                  table:{
                      body:[
                          [{text:'REGISTROS DE SISTEMA',alignment:'center',bold:true,fillColor:'#ddd',colSpan:7},{text:''},{text:''},{text:''},{text:''},{text:''},{text:''},],
                          [{text:'CLAVE',alignment:'center',bold:true,fillColor:'#ddd'},{text:'NOMBRE DEL FORMATO',alignment:'center',bold:true,fillColor:'#ddd'},{text:'FECHA DE EMISIÓN',alignment:'center',bold:true,fillColor:'#ddd'},{text:'NO. DE REVISIÓN',alignment:'center',bold:true,fillColor:'#ddd'},{text:'DISPOSICIÓN',alignment:'center',bold:true,fillColor:'#ddd'},{text:'TIEMPO DE RETENCIÓN',alignment:'center',bold:true,fillColor:'#ddd'},{text:'PROCEDIIENTO ASOCIADO',alignment:'center',bold:true,fillColor:'#ddd'},],
                          [{text:'FS-01'},{text:'PROCEDIMIENTOS, PRACTICAS, INSTRUCTIVO, METODOLOGÍA'},{text:`${this.datos.c13p1}`},{text:`${this.datos.c13p2}`},{text:`${this.datos.c13p3}`},{text:`${this.datos.c13p4}`},{text:`${this.datos.c13p5}`}],         
                          [{text:'FS-02'},{text:'LISTA MAESTRA DE DOCUMENTOS INTERNOS'},{text:`${this.datos.c13p6}`},{text:`${this.datos.c13p7}`},{text:`${this.datos.c13p8}`},{text:`${this.datos.c13p9}`},{text:`${this.datos.c13p10}`}],                        
                          [{text:'FS-03'},{text:'SOLICITUD DE CAMBIOS'},{text:`${this.datos.c13p11}`},{text:`${this.datos.c13p12}`},{text:`${this.datos.c13p13}`},{text:`${this.datos.c13p14}`},{text:`${this.datos.c13p15}`}],                                          
                          [{text:'FS-04'},{text:'LISTA DE DISTRIBUCIÓN DE DOCUMENTOS'},{text:`${this.datos.c14p1}`},{text:`${this.datos.c14p2}`},{text:`${this.datos.c14p3}`},{text:`${this.datos.c14p4}`},{text:`${this.datos.c14p5}`}],     
                          [{text:'FS-05'},{text:'LISTA DE COMUNICACIÓN'},{text:`${this.datos.c14p6}`},{text:`${this.datos.c14p7}`},{text:`${this.datos.c14p8}`},{text:`${this.datos.c14p9}`},{text:`${this.datos.c14p10}`}],    
                          [{text:'FS-06'},{text:'QUEJAS Y SUGERENCIAS'},{text:`${this.datos.c14p11}`},{text:`${this.datos.c14p12}`},{text:`${this.datos.c14p13}`},{text:`${this.datos.c14p14}`},{text:`${this.datos.c14p15}`}],
                          [{text:'FS-07'},{text:'REGISTRO Y CONTROL DE QUEJAS Y SUGERENCIAS'},{text:`${this.datos.c15p1}`},{text:`${this.datos.c15p2}`},{text:`${this.datos.c15p3}`},{text:`${this.datos.c15p4}`},{text:`${this.datos.c15p5}`}],     
                          [{text:'FS-08'},{text:'EVALUACIÓN DE ASPECTOS AMBIENTALES'},{text:`${this.datos.c15p6}`},{text:`${this.datos.c15p7}`},{text:`${this.datos.c15p8}`},{text:`${this.datos.c15p9}`},{text:`${this.datos.c15p10}`}],    
                          [{text:'FS-09'},{text:'EVALUACIÓN DE RIESGOS'},{text:`${this.datos.c15p11}`},{text:`${this.datos.c15p12}`},{text:`${this.datos.c15p13}`},{text:`${this.datos.c15p14}`},{text:`${this.datos.c15p15}`}],
                          [{text:'FS-10'},{text:'RESULTADO DEL ANÁLISIS DE RISGOS'},{text:`${this.datos.c16p1}`},{text:`${this.datos.c16p2}`},{text:`${this.datos.c16p3}`},{text:`${this.datos.c16p4}`},{text:`${this.datos.c16p5}`}],     
                          [{text:'FS-11'},{text:'LISTADO DE RIESGOS Y ASPECTOS AMBIENTALES'},{text:`${this.datos.c16p6}`},{text:`${this.datos.c16p7}`},{text:`${this.datos.c16p8}`},{text:`${this.datos.c16p9}`},{text:`${this.datos.c16p10}`}],    
                          [{text:'FS-12'},{text:'OBJETIVOS Y METAS E INDICADORES'},{text:`${this.datos.c16p11}`},{text:`${this.datos.c16p12}`},{text:`${this.datos.c17p16}`},{text:`${this.datos.c16p14}`},{text:`${this.datos.c16p15}`}],
                          [{text:'FS-13'},{text:'MATRIZ DE RESPONSABILIDADES'},{text:`${this.datos.c17p1}`},{text:`${this.datos.c17p2}`},{text:`${this.datos.c17p3}`},{text:`${this.datos.c17p4}`},{text:`${this.datos.c17p5}`}],     
                          [{text:'FS-14'},{text:'PERFIL DEL PUESTO DE TRABAJO'},{text:`${this.datos.c17p6}`},{text:`${this.datos.c17p7}`},{text:`${this.datos.c17p8}`},{text:`${this.datos.c17p9}`},{text:`${this.datos.c17p10}`}],    
                          [{text:'FS-15'},{text:'DETECCION DE NECESIDADES DE CAPACITACIÓN'},{text:`${this.datos.c17p11}`},{text:`${this.datos.c17p12}`},{text:`${this.datos.c17p13}`},{text:`${this.datos.c17p14}`},{text:`${this.datos.c17p15}`}],
                          [{text:'FS-16'},{text:'PROGRAMA DE CAPACITACIÓN'}     ,{text:`${this.datos.c18p1}`},{text:`${this.datos.c18p2}`},{text:`${this.datos.c18p3}`},{text:`${this.datos.c18p4}`},{text:`${this.datos.c18p5}`}],     
                          [{text:'FS-17'},{text:'SEGUIMIENTO AL PROGRAMA DE CAPACITACION'}    ,{text:`${this.datos.c18p6}`},{text:`${this.datos.c18p7}`},{text:`${this.datos.c18p8}`},{text:`${this.datos.c18p9}`},{text:`${this.datos.c18p10}`}],    
                          [{text:'FS-18'},{text:'LISTADO DE CODIGOS Y ESTÁNDARES'},{text:`${this.datos.c18p11}`},{text:`${this.datos.c18p12}`},{text:`${this.datos.c18p13}`},{text:`${this.datos.c18p14}`},{text:`${this.datos.c18p15}`}],
                          [{text:'FS-19'},{text:'ADMINISTRACION DEL CAMBIO DE TECNOLOGÍA'}     ,{text:`${this.datos.c19p1}`},{text:`${this.datos.c19p2}`},{text:`${this.datos.c19p3}`},{text:`${this.datos.c19p4}`},{text:`${this.datos.c19p5}`}],
                          [{text:'FS-20'},{text:'PROGRAMA DE MANTENIMIENTO'}    ,{text:`${this.datos.c19p6}`},{text:`${this.datos.c19p7}`},{text:`${this.datos.c19p8}`},{text:`${this.datos.c19p9}`},{text:`${this.datos.c19p10}`}],
                          [{text:'FS-21'},{text:'PLAN DE MANTENIMIENTO'},{text:`${this.datos.c19p11}`},{text:`${this.datos.c19p12}`},{text:`${this.datos.c19p13}`},{text:`${this.datos.c19p14}`},{text:`${this.datos.c19p15}`}],
                          [{text:'FS-22'},{text:'LISTADO DE EQUIPO CRITICO'}     ,{text:`${this.datos.c20p1}`},{text:`${this.datos.c20p2}`},{text:`${this.datos.c20p3}`},{text:`${this.datos.c20p4}`},{text:`${this.datos.c20p5}`}],
                          [{text:'FS-23'},{text:'LISTADO DE REQUISITOS LEGALES'}    ,{text:`${this.datos.c20p6}`},{text:`${this.datos.c20p7}`},{text:`${this.datos.c20p8}`},{text:`${this.datos.c20p9}`},{text:`${this.datos.c20p10}`}],
                          [{text:'FS-24'},{text:'ANEXO DE SEGURIDAD DE CONTRATISTAS'},{text:`${this.datos.c20p11}`},{text:`${this.datos.c20p12}`},{text:`${this.datos.c20p13}`},{text:`${this.datos.c20p14}`},{text:`${this.datos.c20p15}`}],
                          [{text:'FS-25'},{text:'ACTA DE INTEGRACION DE LAS BRIGADAS'}     ,{text:`${this.datos.c21p1}`},{text:`${this.datos.c21p2}`},{text:`${this.datos.c21p3}`},{text:`${this.datos.c21p4}`},{text:`${this.datos.c21p5}`}],
                          [{text:'FS-26'},{text:'PROGRAMA DE SIMULACROS'}    ,{text:`${this.datos.c21p6}`},{text:`${this.datos.c21p7}`},{text:`${this.datos.c21p8}`},{text:`${this.datos.c21p9}`},{text:`${this.datos.c21p10}`}],
                          [{text:'FS-27'},{text:'PLANEACION DE SIMULACROS'},{text:`${this.datos.c21p11}`},{text:`${this.datos.c21p12}`},{text:`${this.datos.c21p13}`},{text:`${this.datos.c21p14}`},{text:`${this.datos.c21p15}`}],
                          [{text:'FS-28'},{text:'EVALUACION DE SIMULACROS'}     ,{text:`${this.datos.c22p1}`},{text:`${this.datos.c22p2}`},{text:`${this.datos.c22p3}`},{text:`${this.datos.c22p4}`},{text:`${this.datos.c22p5}`}],
                          [{text:'FS-29'},{text:'PROGRAMA DE MONITOREO Y MEDICIÓN DE PARÁMETROS DE DESEMPEÑO'}    ,{text:`${this.datos.c22p6}`},{text:`${this.datos.c22p7}`},{text:`${this.datos.c22p8}`},{text:`${this.datos.c22p9}`},{text:`${this.datos.c22p10}`}],
                          [{text:'FS-30'},{text:'RESULTADOS DEL MONITOREO DE PARÁMETROS DEL DESEMPEÑO'},{text:`${this.datos.c22p11}`},{text:`${this.datos.c22p12}`},{text:`${this.datos.c22p13}`},{text:`${this.datos.c22p14}`},{text:`${this.datos.c22p15}`}],
                          [{text:'FS-31'},{text:'EVALUACIÓN DEL CUMPLIMIENTO DE LOS REQUISITOS LEGALES'}     ,{text:`${this.datos.c23p1}`},{text:`${this.datos.c23p2}`},{text:`${this.datos.c23p3}`},{text:`${this.datos.c23p4}`},{text:`${this.datos.c23p5}`}],
                          [{text:'FS-32'},{text:'PLAN DE ATENCIÓN DE HALLAZGOS DERIVADOS DEL MONITOREO DEL SA'}    ,{text:`${this.datos.c23p6}`},{text:`${this.datos.c23p7}`},{text:`${this.datos.c23p8}`},{text:`${this.datos.c23p9}`},{text:`${this.datos.c23p10}`}],
                          [{text:'FS-33'},{text:'PROGRAMA DE AUDITORIAS'},{text:`${this.datos.c23p11}`},{text:`${this.datos.c23p12}`},{text:`${this.datos.c23p13}`},{text:`${this.datos.c23p14}`},{text:`${this.datos.c23p15}`}],
                          [{text:'FS-34'},{text:'PLAN DE AUDITORIA'}     ,{text:`${this.datos.c24p1}`},{text:`${this.datos.c24p2}`},{text:`${this.datos.c24p3}`},{text:`${this.datos.c24p4}`},{text:`${this.datos.c24p5}`}],
                          [{text:'FS-35'},{text:'INFORME DE AUDITORIA'}    ,{text:`${this.datos.c24p6}`},{text:`${this.datos.c24p7}`},{text:`${this.datos.c24p8}`},{text:`${this.datos.c24p9}`},{text:`${this.datos.c24p10}`}],
                          [{text:'FS-36'},{text:'PLAN DE ATENCION DE HALLAZGOS'},{text:`${this.datos.c24p11}`},{text:`${this.datos.c24p12}`},{text:`${this.datos.c24p13}`},{text:`${this.datos.c24p14}`},{text:`${this.datos.c24p15}`}],
                          [{text:'FS-37'},{text:'REVISION POR LA DIRECCIÓN'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-01'},{text:'INSPECCION DE TANQUES Y REGISTROS'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-02'},{text:'PRUEBA OPERATIVA DE DISPOSITIVOS DE SEGURIDAD'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-03'},{text:'INSPECCION DE DISPENSARIOS'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-04'},{text:'INSPECCION DE ACCESORIOS DE DESCARGA Y TUBOS DE VENTEO'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-05'},{text:'INSPECCION DE INSTALACIONES ELECTRICAS'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-06'},{text:'PROGRAMA DE LIMPIEZA Y VERIFICACION DE TRAMPA DE COMBUSTIBLE'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-07'},{text:'INSPECCION MENSUAL DE EXTINTORES'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-08'},{text:'INSPECCION DE SEÑALAMIENTOS'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-09'},{text:'PERMISO DE TRABAJO PELIGROSO'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-10'},{text:'FORMATO PARA ACR'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-11'},{text:'ENTREVISTA DE PERSONAL'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-12'},{text:'COMPROBACION DE HIPOTESIS'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-13'},{text:'RECOMENDACIONES DE LA ICR'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          [{text:'FO-14'},{text:'ESTADÍSTICA DE INCIDENTES'},{text:''},{text:''},{text:''},{text:''},{text:''}],
                          ]
                  }
              }
               ]
     ,
     
      pageSize: 'LETTER',pageOrientation: 'landscape',
      pageMargins: [22,110]
  };
  this.pdfMaker.generate(dd, 'VII Solicitud de cambios');
  }
  
}
